# ~/.config/foot/foot.ini
font=Noto Sans Mono:size=10, Noto Color Emoji:size=10

[main]
pad=20x20 center

[colors-dark]
alpha=0.90

foreground=e3e3ea
background=0c0c19
selection-foreground=2c2c2c
selection-background=ffffff

## Regular colors (0-7)
regular0=000000 # black
regular1=ff7f7f # red
regular2=7f3fbf # green (purple)
regular3=cc3980 # yellow
regular4=7f7fff # blue
regular5=7f3fbf # magenta
regular6=7f7fff # cyan
regular7=e3e3ea # white

## Bright colors (8-15)
bright0=3535b1 # bright black (light purple)
bright1=ff7f7f # bright red
bright2=ffd8d8 # bright green
bright3=ff7f7f # bright yellow
bright4=9898ff # bright blue
bright5=7f3fbf # bright magenta
bright6=7f7fff # bright cyan
bright7=ffffff # bright white
