#!/usr/bin/env bash
# Maintainer: joekamprad [joekamprad //a_t// endeavouros.com]
username="$1"
git clone https://codeberg.org/joekamprad/endeavouros-sway-setup.git
cd endeavouros-sway-setup/etc/skel/
cp -R .config .local /home/$username/
cp  .bashrc .gtkrc-2.0 packages-repository.txt packages-AUR.txt /home/$username/
cp packages-AUR.txt /home/$username/
chown -R $username:$username /home/$username
chmod -R +x /home/$username/.config/sway/scripts
pacman -S --needed --noconfirm - < packages-repository.txt 
cd ..
rm -R endeavouros-sway-setup
systemctl enable ly