#!/usr/bin/env bash

# simple yad gui to show default EndeavourOS sway keybindings

Main() {

    local command=(
        yad --title="EndeavourOS SWAY keybindings:" --no-buttons --geometry=400x300-15-400 --list
        --column-align="lcc"
        --header-align="ccc"
        --column="key combination" --column="description" --column=""
        "ESC" "close this app" ""
        "=" "set mod-key to the win-key" ""
        "+enter" "open a terminal" ""
        "+Shift+n" "new empty workspace" ""
        "+w" "open Browser" ""
        "+n" "open Filebrowser" ""
        "+d" "app menu" ""
        "+q" "close focused app" ""
        "Print-key" "screenshot" ""
        "+Shift+e" "logout menu" ""
        "F1" "open keybinding helper" ""
    )

    "${command[@]}"
}

Main "$@"
