#!/bin/bash

STATEFILE="/tmp/waybar_toggle.state"

if pgrep -x waybar > /dev/null; then
    # Waybar runs = kill
    killall waybar
    echo "off" > "$STATEFILE"
else
# Waybar does not run = start all 3 instances
    waybar -c ~/.config/waybar/config_br.jsonc -s ~/.config/waybar/style_br.css &
    waybar -c ~/.config/waybar/config_tl.jsonc -s ~/.config/waybar/style_tl.css &
    waybar -c ~/.config/waybar/config_bl.jsonc -s ~/.config/waybar/style_bl.css &
    echo "on" > "$STATEFILE"
fi

